# Generated by Django 3.1.5 on 2021-06-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210608_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
