# Generated by Django 3.2.4 on 2021-06-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210608_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
