# Generated by Django 3.2.4 on 2021-06-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_detail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
